FROM node:lts-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json yarn.lock ./

RUN yarn install

COPY ./src ./
COPY ./public ./
COPY ./jsconfig.json ./
COPY ./README.md ./

CMD ["yarn", "start"]